version: "3.8"
services:
  cassandra11:
    image: cassandra:4.1
    container_name: cassandra11
    hostname: cassandra11
    mem_limit: 1g
    #cpus: 1.0
    restart: always
    volumes:
      - cassandra11:/var/lib/cassandra      
      #- "/home/user/cassandra11:/etc/cassandra:rw" 
      #- "d:\cassandra01_data:/var/lib/cassandra:rw"   
      #- "/home/user/cassandra11/data:/var/lib/cassandra:rw"
    environment:
      - CASSANDRA_CLUSTER_NAME=Cluster_Formation
      - CASSANDRA_NUM_TOKENS=16   
      - CASSANDRA_SEEDS=cassandra11,cassandra12
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_DC=NORD
      - CASSANDRA_RACK=WINTERFELL1
      - CASSANDRA_BROADCAST_RPC_ADDRESS=127.0.0.1
      - CASSANDRA_NATIVE_TRANSPORT_PORT=9042
      - MAX_HEAP_SIZE=256m
      - HEAP_NEWSIZE=50m  
    ports:
      - "9042:9042"
    healthcheck:
      #test: ["CMD", "nc", "-z", "127.0.0.1", "9042"]
      test: ["CMD", "cqlsh", "-e", "describe keyspaces", "127.0.0.1", "9042" ]  
      #test: ["CMD-SHELL", "[ $$(nodetool -h 127.0.0.1 -pw cassandra -u cassandra statusgossip) = running ]"]
      interval: 5s
      timeout: 5s
      retries: 60
      #start_period: 60s

  cassandra12:
    depends_on:
      cassandra11:
        condition: service_healthy
    image: cassandra:4.1
    container_name: cassandra12
    hostname: cassandra12
    mem_limit: 1g
    #cpus: 1.0
    restart: always
    volumes:
      - cassandra12:/var/lib/cassandra
      #- "/home/user/cassandra12/data:/var/lib/cassandra:rw"
    environment:
      - CASSANDRA_CLUSTER_NAME=Cluster_Formation
      - CASSANDRA_NUM_TOKENS=16   
      - CASSANDRA_SEEDS=cassandra11,cassandra12
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_DC=TERRES-DE-LA-COURONNE
      - CASSANDRA_RACK=PORT-REAL1
      - CASSANDRA_BROADCAST_RPC_ADDRESS=127.0.0.1
      - CASSANDRA_NATIVE_TRANSPORT_PORT=9043
      - MAX_HEAP_SIZE=256m
      - HEAP_NEWSIZE=50m  
    ports:
      - "9043:9043"
    healthcheck:
      #test: ["CMD", "nc", "-z", "127.0.0.1", "9042"]
      test: ["CMD", "cqlsh", "-e", "describe keyspaces", "127.0.0.1", "9042" ]  
      #test: ["CMD-SHELL", "[ $$(nodetool -h 127.0.0.1 -pw cassandra -u cassandra statusgossip) = running ]"]
      interval: 5s
      timeout: 5s
      retries: 60
      #start_period: 60s

  cassandra13:
    depends_on:
      cassandra12:
        condition: service_healthy
    image: cassandra:4.1
    container_name: cassandra13
    hostname: cassandra13
    mem_limit: 1g
    #cpus: 1.0
    restart: always
    volumes:
      - cassandra13:/var/lib/cassandra
      #- "/home/user/cassandra13/data:/var/lib/cassandra:rw"
    environment:
      - CASSANDRA_CLUSTER_NAME=Cluster_Formation
      - CASSANDRA_NUM_TOKENS=16   
      - CASSANDRA_SEEDS=cassandra11,cassandra12
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_DC=NORD
      - CASSANDRA_RACK=WINTERFELL2
      - CASSANDRA_BROADCAST_RPC_ADDRESS=127.0.0.1
      - CASSANDRA_NATIVE_TRANSPORT_PORT=9044
      - MAX_HEAP_SIZE=256m
      - HEAP_NEWSIZE=50m  
    ports:
      - "9044:9044"
    healthcheck:
      #test: ["CMD", "nc", "-z", "127.0.0.1", "9042"]
      test: ["CMD", "cqlsh", "-e", "describe keyspaces", "127.0.0.1", "9042" ]  
      #test: ["CMD-SHELL", "[ $$(nodetool -h 127.0.0.1 -pw cassandra -u cassandra statusgossip) = running ]"]
      interval: 5s
      timeout: 5s
      retries: 60
      #start_period: 60s

  cassandra14:
    depends_on:
      cassandra13:
        condition: service_healthy
    image: cassandra:4.1
    container_name: cassandra14
    hostname: cassandra14
    mem_limit: 1g
    #cpus: 1.0
    restart: always
    volumes:
      - cassandra14:/var/lib/cassandra
      #- "/home/user/cassandra14/data:/var/lib/cassandra:rw"
    environment:
      - CASSANDRA_CLUSTER_NAME=Cluster_Formation
      - CASSANDRA_NUM_TOKENS=16   
      - CASSANDRA_SEEDS=cassandra11,cassandra12
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_DC=TERRES-DE-LA-COURONNE
      - CASSANDRA_RACK=PORT-REAL2
      - CASSANDRA_BROADCAST_RPC_ADDRESS=127.0.0.1
      - CASSANDRA_NATIVE_TRANSPORT_PORT=9045
      - MAX_HEAP_SIZE=256m
      - HEAP_NEWSIZE=50m  
    ports:
      - "9045:9045"
    healthcheck:
      #test: ["CMD", "nc", "-z", "127.0.0.1", "9042"]
      test: ["CMD", "cqlsh", "-e", "describe keyspaces", "127.0.0.1", "9042" ]  
      #test: ["CMD-SHELL", "[ $$(nodetool -h 127.0.0.1 -pw cassandra -u cassandra statusgossip) = running ]"]
      interval: 5s
      timeout: 5s
      retries: 60
      #start_period: 60s

  cassandra15:
    depends_on:
      cassandra14:
        condition: service_healthy
    image: cassandra:4.1
    container_name: cassandra15
    hostname: cassandra15
    mem_limit: 1g
    #cpus: 1.0
    restart: always
    volumes:
      - cassandra15:/var/lib/cassandra
      #- "/home/user/cassandra15/data:/var/lib/cassandra:rw"
    environment:
      - CASSANDRA_CLUSTER_NAME=Cluster_Formation
      - CASSANDRA_NUM_TOKENS=16   
      - CASSANDRA_SEEDS=cassandra11,cassandra12
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_DC=NORD
      - CASSANDRA_RACK=WINTERFELL3
      - CASSANDRA_BROADCAST_RPC_ADDRESS=127.0.0.1
      - CASSANDRA_NATIVE_TRANSPORT_PORT=9046
      - MAX_HEAP_SIZE=256m
      - HEAP_NEWSIZE=50m  
    ports:
      - "9046:9046"
    healthcheck:
      #test: ["CMD", "nc", "-z", "127.0.0.1", "9042"]
      test: ["CMD", "cqlsh", "-e", "describe keyspaces", "127.0.0.1", "9042" ]  
      #test: ["CMD-SHELL", "[ $$(nodetool -h 127.0.0.1 -pw cassandra -u cassandra statusgossip) = running ]"]
      interval: 5s
      timeout: 5s
      retries: 60
      #start_period: 60s

  cassandra16:
    depends_on:
      cassandra15:
        condition: service_healthy
    image: cassandra:4.1
    container_name: cassandra16
    hostname: cassandra16
    mem_limit: 1g
    #cpus: 1.0
    restart: always
    volumes:
      - cassandra16:/var/lib/cassandra
      #- "/home/user/cassandra16/data:/var/lib/cassandra:rw"
    environment:
      - CASSANDRA_CLUSTER_NAME=Cluster_Formation
      - CASSANDRA_NUM_TOKENS=16   
      - CASSANDRA_SEEDS=cassandra11,cassandra12
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_DC=TERRES-DE-LA-COURONNE
      - CASSANDRA_RACK=PORT-REAL3
      - CASSANDRA_BROADCAST_RPC_ADDRESS=127.0.0.1
      - CASSANDRA_NATIVE_TRANSPORT_PORT=9047
      - MAX_HEAP_SIZE=256m
      - HEAP_NEWSIZE=50m  
    ports:
      - "9047:9047"
    healthcheck:
      #test: ["CMD", "nc", "-z", "127.0.0.1", "9042"]
      test: ["CMD", "cqlsh", "-e", "describe keyspaces", "127.0.0.1", "9042" ]   
      #test: ["CMD-SHELL", "[ $$(nodetool -h 127.0.0.1 -pw cassandra -u cassandra statusgossip) = running ]"]
      interval: 5s
      timeout: 5s
      retries: 60
      #start_period: 60s

volumes:
  cassandra11:
  cassandra12:
  cassandra13:
  cassandra14:
  cassandra15:
  cassandra16:
