version: "3.8"
services:
  cassandra11:
    image: cassandra:4.1
    container_name: cassandra11
    hostname: cassandra11
    mem_limit: 1g
    #cpus: 1.0
    restart: always
    volumes:
      - cassandra11:/var/lib/cassandra
      #- "/home/user/cassandra11:/etc/cassandra:rw" 
      #- "d:\cassandra11_data:/var/lib/cassandra:rw"   
      #- "/home/user/cassandra11/data:/var/lib/cassandra:rw"
    environment:
      - CASSANDRA_CLUSTER_NAME=ClusterFormation
      - CASSANDRA_NUM_TOKENS=16  
      - CASSANDRA_SEEDS=cassandra11,cassandra21
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_DC=NORD
      - CASSANDRA_RACK=WINTERFELL1
      - CASSANDRA_BROADCAST_RPC_ADDRESS=127.0.0.1
      - CASSANDRA_NATIVE_TRANSPORT_PORT=9042
      - MAX_HEAP_SIZE=256m
      - HEAP_NEWSIZE=50m  
    ports:
      - "9042:9042"
    healthcheck:
      #test: ["CMD", "nc", "-z", "127.0.0.1", "9042"]
      test: ["CMD", "cqlsh", "-e", "describe keyspaces", "cassandra11", "9042" ]  
      #test: ["CMD-SHELL", "[ $$(nodetool -h 127.0.0.1 -pw cassandra -u cassandra statusgossip) = running ]"]
      interval: 5s
      timeout: 5s
      retries: 60
      #start_period: 60s

  cassandra12:
    depends_on:
      cassandra11:
        condition: service_healthy
    image: cassandra:4.1
    container_name: cassandra12
    hostname: cassandra12
    mem_limit: 1g
    #cpus: 1.0
    restart: always    
    volumes:    
      - cassandra12:/var/lib/cassandra
      #- "/home/user/cassandra12/data:/var/lib/cassandra:rw"
    environment:
      - CASSANDRA_CLUSTER_NAME=ClusterFormation
      - CASSANDRA_NUM_TOKENS=16  
      - CASSANDRA_SEEDS=cassandra11,cassandra21
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_DC=NORD
      - CASSANDRA_RACK=WINTERFELL2
      - CASSANDRA_BROADCAST_RPC_ADDRESS=127.0.0.1
      - CASSANDRA_NATIVE_TRANSPORT_PORT=9042
      - MAX_HEAP_SIZE=256m
      - HEAP_NEWSIZE=50m  
    ports:
      - "9043:9042"
    healthcheck:
      #test: ["CMD", "nc", "-z", "127.0.0.1", "9042"]
      test: ["CMD", "cqlsh", "-e", "describe keyspaces", "cassandra12", "9042" ]  
      #test: ["CMD-SHELL", "[ $$(nodetool -h 127.0.0.1 -pw cassandra -u cassandra statusgossip) = running ]"]
      interval: 5s
      timeout: 5s
      retries: 60
      #start_period: 60s

  cassandra13:
    depends_on:
      cassandra12:
        condition: service_healthy
    image: cassandra:4.1
    container_name: cassandra13
    hostname: cassandra13
    mem_limit: 1g
    #cpus: 1.0
    restart: always
    volumes:
      - cassandra13:/var/lib/cassandra
      #- "/home/user/cassandra13/data:/var/lib/cassandra:rw"
    environment:
      - CASSANDRA_CLUSTER_NAME=ClusterFormation
      - CASSANDRA_NUM_TOKENS=16  
      - CASSANDRA_SEEDS=cassandra11,cassandra21
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_DC=NORD
      - CASSANDRA_RACK=WINTERFELL3
      - CASSANDRA_BROADCAST_RPC_ADDRESS=127.0.0.1
      - CASSANDRA_NATIVE_TRANSPORT_PORT=9042
      - MAX_HEAP_SIZE=256m
      - HEAP_NEWSIZE=50m  
    ports:
      - "9044:9042"
    healthcheck:
      #test: ["CMD", "nc", "-z", "127.0.0.1", "9042"]
      test: ["CMD", "cqlsh", "-e", "describe keyspaces", "cassandra13", "9042" ]  
      #test: ["CMD-SHELL", "[ $$(nodetool -h 127.0.0.1 -pw cassandra -u cassandra statusgossip) = running ]"]
      interval: 5s
      timeout: 5s
      retries: 60
      #start_period: 60s

  cassandra21:
    depends_on:
      cassandra13:
        condition: service_healthy  
    image: cassandra:4.1
    container_name: cassandra21
    hostname: cassandra21
    mem_limit: 1g
    #cpus: 1.0
    restart: always
    volumes:
      - cassandra21:/var/lib/cassandra
      #- "/home/user/cassandra21/data:/var/lib/cassandra:rw"
    environment:
      - CASSANDRA_CLUSTER_NAME=ClusterFormation
      - CASSANDRA_NUM_TOKENS=16  
      - CASSANDRA_SEEDS=cassandra11,cassandra21
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_DC=TERRES-DE-LA-COURONNE
      - CASSANDRA_RACK=PORT-REAL1
      - CASSANDRA_BROADCAST_RPC_ADDRESS=127.0.0.1
      - CASSANDRA_NATIVE_TRANSPORT_PORT=9042
      - MAX_HEAP_SIZE=256m
      - HEAP_NEWSIZE=50m  
    ports:
      - "9045:9042"
    healthcheck:
      #test: ["CMD", "nc", "-z", "127.0.0.1", "9042"]
      test: ["CMD", "cqlsh", "-e", "describe keyspaces", "cassandra21", "9042" ]  
      #test: ["CMD-SHELL", "[ $$(nodetool -h 127.0.0.1 -pw cassandra -u cassandra statusgossip) = running ]"]
      interval: 5s
      timeout: 5s
      retries: 60
      #start_period: 60s

  cassandra22:
    depends_on:
      cassandra21:
        condition: service_healthy  
    image: cassandra:4.1
    container_name: cassandra22
    hostname: cassandra22
    mem_limit: 1g
    #cpus: 1.0
    restart: always
    volumes:
      - cassandra22:/var/lib/cassandra
      #- "/home/user/cassandra22/data:/var/lib/cassandra:rw"
    environment:
      - CASSANDRA_CLUSTER_NAME=ClusterFormation
      - CASSANDRA_NUM_TOKENS=16  
      - CASSANDRA_SEEDS=cassandra11,cassandra21
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_DC=TERRES-DE-LA-COURONNE
      - CASSANDRA_RACK=PORT-REAL2
      - CASSANDRA_BROADCAST_RPC_ADDRESS=127.0.0.1
      - CASSANDRA_NATIVE_TRANSPORT_PORT=9042
      - MAX_HEAP_SIZE=256m
      - HEAP_NEWSIZE=50m  
    ports:
      - "9046:9042"
    healthcheck:
      #test: ["CMD", "nc", "-z", "127.0.0.1", "9042"]
      test: ["CMD", "cqlsh", "-e", "describe keyspaces", "cassandra22", "9042" ]   
      #test: ["CMD-SHELL", "[ $$(nodetool -h 127.0.0.1 -pw cassandra -u cassandra statusgossip) = running ]"]
      interval: 5s
      timeout: 5s
      retries: 60
      #start_period: 60s

  cassandra23:
    depends_on:
      cassandra22:
        condition: service_healthy  
    image: cassandra:4.1
    container_name: cassandra23
    hostname: cassandra23
    mem_limit: 1g
    #cpus: 1.0
    restart: always
    volumes:
      - cassandra23:/var/lib/cassandra
      #- "/home/user/cassandra23/data:/var/lib/cassandra:rw"
    environment:
      - CASSANDRA_CLUSTER_NAME=ClusterFormation
      - CASSANDRA_NUM_TOKENS=16  
      - CASSANDRA_SEEDS=cassandra11,cassandra21
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_DC=TERRES-DE-LA-COURONNE
      - CASSANDRA_RACK=PORT-REAL3
      - CASSANDRA_BROADCAST_RPC_ADDRESS=127.0.0.1
      - CASSANDRA_NATIVE_TRANSPORT_PORT=9042
      - MAX_HEAP_SIZE=256m
      - HEAP_NEWSIZE=50m  
    ports:
      - "9047:9042"
    healthcheck:
      #test: ["CMD", "nc", "-z", "127.0.0.1", "9042"]
      test: ["CMD", "cqlsh", "-e", "describe keyspaces", "cassandra23", "9042" ]    
      #test: ["CMD-SHELL", "[ $$(nodetool -h 127.0.0.1 -pw cassandra -u cassandra statusgossip) = running ]"]
      interval: 5s
      timeout: 5s
      retries: 60
      #start_period: 60s

volumes:
  cassandra11:
  cassandra12:
  cassandra13:
  cassandra21:
  cassandra22:
  cassandra23:
